# Generated by Django 6.0.2 on 2026-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100, verbose_name='Time Mandante')),
                ('away_team', models.CharField(max_length=100, verbose_name='Time Visitante')),
                ('favorite_team', models.CharField(max_length=100, verbose_name='Time Favorito')),
                ('match_date', models.DateField(verbose_name='Data da Partida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fav_goals_history', models.JSONField(default=list, verbose_name='Gols feitos (Últimos 5)')),
                ('fav_shots_h1_history', models.JSONField(default=list, verbose_name='Finalizações 1T (Últimos 5)')),
                ('fav_corners_h1_history', models.JSONField(default=list, verbose_name='Escanteios 1T (Últimos 5)')),
                ('underdog_goals_conceded_history', models.JSONField(default=list, verbose_name='Gols sofridos (Últimos 5)')),
                ('underdog_shots_conceded_h1_history', models.JSONField(default=list, verbose_name='Finalizações sofridas 1T (Últimos 5)')),
                ('underdog_corners_conceded_h1_history', models.JSONField(default=list, verbose_name='Escanteios sofridos 1T (Últimos 5)')),
                ('prediction_goals', models.FloatField(blank=True, null=True, verbose_name='Previsão de Gols')),
                ('prediction_shots_h1', models.FloatField(blank=True, null=True, verbose_name='Previsão Finalizações 1T')),
                ('prediction_corners_h1', models.FloatField(blank=True, null=True, verbose_name='Previsão Escanteios 1T')),
            ],
            options={
                'verbose_name': 'Partidas',
                'ordering': ['-match_date'],
            },
        ),
    ]
