# Generated by Django 6.0.2 on 2026-02-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_away',
            field=models.BooleanField(default=False, verbose_name='Favorito é Visitante?'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('Bundesliga', 'Bundesliga'), ('Saudi_Pro_League', 'Saudi Pro League'), ('Jupiler_League', 'Jupiler League'), ('Brasileirao', 'Brasileirao'), ('La_Liga', 'La Liga'), ('Ligue_1', 'Ligue 1'), ('Premier_League', 'Premier League'), ('Championship', 'Championship'), ('Serie_A', 'Serie A'), ('Eredivisie', 'Eredivisie'), ('Liga_Portugal', 'Liga Portugal'), ('Super_Lig', 'Super Lig')], default='Brasileirao', max_length=100, verbose_name='Campeonato'),
        ),
    ]
